/* eslint-disable */
/**
 * AUTOGENERATED — do not edit.
 * Source: schema/diagram.schema.json
 */

/**
 * A node-based architecture spec file.
 */
export interface LoomDiagram {
  $schema?: string;
  version: "1";
  /**
   * Diagram identifier. Should match the filename without extension.
   */
  id: string;
  title: string;
  description?: string;
  nodes: Node[];
  edges: Edge[];
  groups?: Group[];
}
export interface Node {
  /**
   * Unique within this diagram.
   */
  id: string;
  /**
   * References a key in node-types.json.
   */
  type: string;
  label: string;
  /**
   * Markdown allowed.
   */
  description?: string;
  position: {
    x: number;
    y: number;
  };
  /**
   * planned = spec exists, code does not. implemented = both present. stale = code refs are broken, needs review. deprecated = kept for history, no longer active.
   */
  status: "planned" | "implemented" | "stale" | "deprecated";
  code_refs?: CodeRef[];
  /**
   * Custom fields defined by the node's type in node-types.json.
   */
  properties?: {
    [k: string]: unknown;
  };
  tags?: string[];
  /**
   * ID of another diagram file to navigate into when this node is opened.
   */
  drill_down?: string;
}
export interface CodeRef {
  /**
   * Repo-relative file path.
   */
  path: string;
  /**
   * Function, class, or component name. Preferred over lines because it survives refactors.
   */
  symbol?: string;
  /**
   * Line range(s) like '1-80' or '12,45-50'. Use only when no symbol applies.
   */
  lines?: string;
  /**
   * Canonical signature line captured from the symbol's source. Filled by `loom-spec validate --capture`. Drift detection compares this against the current source; mismatch = warning. Lets agents catch semantic refactors (e.g. parameter type changes) that the existence check alone misses.
   */
  signature_hint?: string;
}
export interface Edge {
  id: string;
  /**
   * Source node id, optionally with :port-name suffix.
   */
  from: string;
  /**
   * Target node id, optionally with :port-name suffix.
   */
  to: string;
  kind: "request" | "event" | "data-read" | "data-write" | "signal" | "dependency" | "control";
  label?: string;
  description?: string;
  direction?: "forward" | "bidirectional";
  /**
   * Free-form architectural attributes for this edge. Loom-spec doesn't enforce a vocabulary — use project conventions (e.g. { sync: false, retry: 'exponential', timeout_ms: 5000, idempotent: true }). Stays out of the way for projects that don't need them.
   */
  properties?: {
    [k: string]: unknown;
  };
}
export interface Group {
  id: string;
  label: string;
  /**
   * Node ids contained in this group.
   */
  children?: string[];
  /**
   * Group ids nested inside this group.
   */
  subgroups?: string[];
  color?: string;
  collapsed?: boolean;
  drill_down?: string;
}
