/* eslint-disable */
/**
 * AUTOGENERATED — do not edit.
 * Source: schema/journey.schema.json
 */

/**
 * An ordered, untimed walkthrough of a diagram. Each step references a node; the renderer highlights nodes one at a time as the reader advances.
 */
export interface LoomJourney {
  $schema?: string;
  version: "1";
  /**
   * Journey identifier. Should match the filename without extension.
   */
  id: string;
  title: string;
  /**
   * Markdown allowed. Renders above the step list.
   */
  description?: string;
  /**
   * ID of the diagram this journey walks through. Every step.node must exist in this diagram.
   */
  diagram: string;
  steps: JourneyStep[];
}
export interface JourneyStep {
  /**
   * Unique within this journey.
   */
  id: string;
  /**
   * ID of a node in the journey's diagram. Validated by the server / MCP tools.
   */
  node: string;
  title?: string;
  /**
   * Markdown allowed. Narrates what happens at this step.
   */
  description?: string;
  /**
   * Optional step-level code refs. Use to narrow focus to a specific symbol within the node's code; if redundant with the node's code_refs, omit.
   */
  code_refs?: CodeRef[];
}
export interface CodeRef {
  /**
   * Repo-relative file path.
   */
  path: string;
  /**
   * Function, class, or component name. Preferred over lines because it survives refactors.
   */
  symbol?: string;
  /**
   * Line range(s) like '1-80' or '12,45-50'. Use only when no symbol applies.
   */
  lines?: string;
  /**
   * Canonical signature line captured from the symbol's source. Filled by `loom-spec validate --capture`. Drift detection compares this against the current source; mismatch = warning.
   */
  signature_hint?: string;
  /**
   * Marks this code_ref as running on a real-time / audio thread. `loom-spec validate` scans the referenced symbol's body (C++/C only) for RT-unsafe patterns and reports them as errors.
   */
  realtime?: boolean;
}
