/* eslint-disable */
/**
 * AUTOGENERATED — do not edit.
 * Source: schema/node-types.schema.json
 */

export type Field = {
  [k: string]: unknown;
} & {
  name: string;
  type: "string" | "number" | "boolean" | "enum" | "markdown" | "code-ref" | "array";
  required?: boolean;
  description?: string;
  default?: unknown;
  /**
   * Required when type is 'enum'.
   */
  values?: unknown[];
  /**
   * Required when type is 'array'.
   */
  items?: "string" | "number";
  min?: number;
  max?: number;
  pattern?: string;
  max_length?: number;
};

/**
 * Defines the node type vocabulary for a project.
 */
export interface LoomNodeTypes {
  $schema?: string;
  types: {
    [k: string]: NodeType;
  };
}
export interface NodeType {
  label: string;
  description?: string;
  color: string;
  /**
   * Lucide icon name.
   */
  icon?: string;
  fields?: Field[];
  ports?: {
    in?: Port[];
    out?: Port[];
  };
}
export interface Port {
  name: string;
  /**
   * Free-form signal type tag, e.g. 'audio', 'midi', 'http', 'control'.
   */
  signal?: string;
}
