/**
 * Generates TypeScript types from the JSON Schema files.
 * Run with: pnpm generate-types
 */
import { compileFromFile } from "json-schema-to-typescript";
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaDir = resolve(here, "../schema");
const outDir = resolve(here, "../src/types");

const targets = [
  { schema: "diagram.schema.json", out: "diagram.ts" },
  { schema: "node-types.schema.json", out: "node-types.ts" },
];

await mkdir(outDir, { recursive: true });

for (const { schema, out } of targets) {
  const ts = await compileFromFile(resolve(schemaDir, schema), {
    bannerComment: `/* eslint-disable */\n/**\n * AUTOGENERATED — do not edit.\n * Source: schema/${schema}\n */`,
    style: { semi: true, singleQuote: false },
  });
  await writeFile(resolve(outDir, out), ts);
  console.log(`✓ ${out}`);
}
